## NUMPY

***Numpy provides effiecient storage |
it also provides ways of handling data for processing |
it is fast |
uses relatively less memory to store data***

In [1]:
import numpy as np

In [2]:
arr = np.array([12, 13, 14, 15, 16])
arr

array([12, 13, 14, 15, 16])

In [3]:
arr = np.array([12, 13, 14, 15, 16], np.int8) # can specify the size of int 
arr # hence useful in memory management

array([12, 13, 14, 15, 16], dtype=int8)

In [4]:
arr = np.array([12, 13, 14, 15, 16], np.int64) # one D array
arr

array([12, 13, 14, 15, 16], dtype=int64)

In [5]:
arr[3]

15

In [6]:
arr = np.array([[12, 13, 14, 15, 16]], np.int8) # two D array
arr

array([[12, 13, 14, 15, 16]], dtype=int8)

In [7]:
arr[0, 3]

15

In [8]:
arr.dtype

dtype('int8')

In [9]:
arr.shape

(1, 5)

In [10]:
arr[0, 3] = 100 # element can be change like this
arr

array([[ 12,  13,  14, 100,  16]], dtype=int8)

In [11]:
arr

array([[ 12,  13,  14, 100,  16]], dtype=int8)

### Array creation method 

In [ ]:
# There are 6 general mechanisms for creating arrays:

# Conversion from other Python structures (i.e. lists and tuples)

# Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

# Replicating, joining, or mutating existing arrays

# Reading arrays from disk, either from standard or custom formats

# Creating arrays from raw bytes through the use of strings or buffers

# Use of special library functions (e.g., random)

 ## Conversion from other Python structures

In [14]:
list_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
list_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
list_array.dtype

dtype('int32')

In [17]:
list_array.shape

(3, 3)

In [20]:
list_array.max()

9

In [21]:
list_array.min()

1

In [22]:
list_array.mean()

5.0

In [26]:
list_array.size

9

In [28]:
dic = np.array({12, 23, 34, 45, 56, 67, 78})
dic

array({34, 67, 23, 56, 12, 45, 78}, dtype=object)

In [36]:
dic

array({34, 67, 23, 56, 12, 45, 78}, dtype=object)

In [37]:
tup = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10)) # from tuple
tup

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
tup.dtype

dtype('int32')

In [39]:
tup.max()

10

In [40]:
tup.shape

(10,)

In [41]:
tup.size

10

In [42]:
tup.mean()

5.5

In [43]:
tup.min()

1

## Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [ ]:
# zeros

In [47]:
zeros = np.zeros((10, 10))
zeros # make array made of zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
# arange
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# linspace -> gives equally spaced element to np array

In [55]:
lspace = np.linspace(1, 20, 50)
lspace

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [ ]:
# empty -> makes 2D array of given size and filled it with random numbers

In [59]:
em = np.empty((5, 4))
em

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])

In [ ]:
# empty_like() -> makes empty array with numbers used in previous code

In [60]:
emp = np.empty_like(lspace)
emp

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [ ]:
# identity() -> gives identity matrix of given size

In [63]:
ide = np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
ide.shape

(3, 3)

In [73]:
ae = np.arange(100)
ae

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [77]:
ae = ae.reshape(2, 50)
ae

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [78]:
ae = ae.ravel() # again change the shape to default
ae

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
twod = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
twod

<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
twod.sum(axis=0)

array([12, 15, 18])

In [7]:
twod.sum(axis=1)

array([ 6, 15, 24])

In [8]:
twod.mean()

5.0

In [ ]:
# transpose-> T

In [10]:
twod.T 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
twod.flat

In [12]:
for i in twod.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [13]:
twod.ndim # returns dimension of your array

2

In [14]:
twod.size # returns the size no. of element

9

## Numpy array Operations

adding two array

In [17]:
arr1 = np.array([1, 2, 3, 4, 5]) # size of both arrays must be same
arr2 = np.array([6, 7, 8, 9, 10])
arr3 = np.add(arr1, arr2)
arr3 

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([ 7,  9, 11, 13, 15])

Subtracting the two arrays

In [20]:
arr4 = np.subtract(arr2, arr1)
arr4

<IPython.core.display.Javascript object>

array([5, 5, 5, 5, 5])

Multiplying the two arrays

In [21]:
arr5 = np.multiply(arr1, arr2)
arr5

<IPython.core.display.Javascript object>

array([ 6, 14, 24, 36, 50])

Dividing the two arrays

In [23]:
arr6 = np.divide(arr1, arr2)
arr6

<IPython.core.display.Javascript object>

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

power() to calculating exponents of an array of numbers

In [28]:
arr7 = np.power(arr1, 3)
arr7

<IPython.core.display.Javascript object>

array([  1,   8,  27,  64, 125], dtype=int8)

power() with two arrays

In [29]:
arr8 = np.power(arr1, arr2)
arr8

<IPython.core.display.Javascript object>

array([      1,     128,    6561,  262144, 9765625], dtype=int32)

mod() function

In [35]:
arr9 = np.mod(np.array([7, 16, 25]), np.array([4, 8, 6])) # remainder nikalta hai
arr9

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([3, 0, 1], dtype=int32)

reciprocal() function

In [32]:
arr10 = np.reciprocal(arr1)
arr10

<IPython.core.display.Javascript object>

array([1, 0, 0, 0, 0], dtype=int32)

remainder() function

In [34]:
arr11 = np.remainder(np.array([7, 16, 25]), np.array([4, 8, 6]))
arr11

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([3, 0, 1], dtype=int32)

if you notice that the mod() and the remainder() gives the same result both can be used alternatively

In [38]:
one = np.array([177, 445, 14421, 2002276, 12])
one.argmax() # returns the index of the maximum element

<IPython.core.display.Javascript object>

3

In [39]:
one.argmin() # returns the index of the minimum element

4

In [41]:
one.argsort() # returns the sorted index array so that if eleemnt are arranged in this indexed order than array would be sorted

array([4, 0, 1, 2, 3], dtype=int64)

In [42]:
np.count_nonzero(one) #returns the count of elements that are non-zeros

<IPython.core.display.Javascript object>

5

In [44]:
one.size

5

In [45]:
one.itemsize

4

In [46]:
one.size * one.itemsize

20

In [48]:
one.tolist() # returns the list

[177, 445, 14421, 2002276, 12]